# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: dart_test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Latest stable version of the Dart SDK.
      - uses: dart-lang/setup-dart@v1

      # Install dependencies
      - name: Install dependencies
        run: dart pub get

      # Verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Strict analyze
      - name: Analyze project source
        run: dart analyze --fatal-infos
